services:
  - type: web
    name: tifto-admin
    env: node
    plan: starter
    buildCommand: NODE_ENV=development npm install --legacy-peer-deps && NODE_ENV=production npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_SERVER_URL
        value: https://ftifto-backend.onrender.com
      - key: NEXT_PUBLIC_WS_SERVER_URL
        value: wss://ftifto-backend.onrender.com

